// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommunityQuiz.Db
{
    public partial class AnswerEvent
    {
        public int Id { get; set; }
        public int UserQuizEventId { get; set; }
        public int AnswerId { get; set; }
        public bool Selection { get; set; }
    }
}