// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommunityQuiz.Db
{
    public partial class Password
    {
        public int UserId { get; set; }
        public string Salt { get; set; }
        public string Hash { get; set; }
    }
}