// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommunityQuiz.Db
{
    public partial class Question
    {
        public int Id { get; set; }
        public int QuizId { get; set; }
        public string Statement { get; set; }
        public bool MultiAnswer { get; set; }
        public double Weighting { get; set; }
    }
}