// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommunityQuiz.Db
{
    public partial class Quiz
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string QuizName { get; set; }
        public bool Published { get; set; }
    }
}