// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommunityQuiz.Db
{
    public partial class Role
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
    }
}